version: "3.7"

services: 
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Castvna88
      - ACCEPT_EULA=Y
      - MSSQL_USERNAME=jhonathan
      - MSSQL_PASSWORD=Muztbahdw
      - MSSQL_DATABASE=principal
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jhonathan
      - MONGO_INITDB_ROOT_PASSWORD=Muztbahdw
      - MONGO_DATABASE=principal
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=Muztbahdw
      - REDIS_DATABASE=principal
    ports:
      - "6379:6379"
