version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_USER=jhonathan
      - MYSQL_PASSWORD=first-mysql
      - MYSQL_DATABASE=first
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - ./localdb/mysql:/docker-entrypoint-initdb.d
